spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://127.0.0.1:3306/gossip_dev?serverTimezone=UTC
server:
  port: 8080


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %p %C: %m%n"
  level:
    site.imcu.gossip : debug

swagger:
  authorization:
    key-name: Token
  enabled: true
##mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  mapper-locations: mapper/*.xml
